Repository nbcamp-spring-junwoo/orz, pull requests merged in 2024-04, with the labels that each got.

#26 🐛 fix(coupon): 동시성 문제 해결 및 동시성 테스트 코드 작성
  src/main/java/com/junwoo/ott/domain/coupon/service/CouponService.java
  src/test/java/com/junwoo/ott/domain/coupon/service/CouponConcurrencyTest.java
  src/test/java/com/junwoo/ott/domain/coupon/test/CouponTestValues.java
Labels: bug

#34 ✨ feat(user): 개인프로필 조회 구현
  src/main/java/com/junwoo/ott/domain/user/controller/UserController.java
Labels: enhancement

#38 🐛 fix(coupon): 배치에 대한 쿠폰 발행 테이블 코드 수정
  src/main/java/com/junwoo/ott/global/batch/CouponIssuanceUpdateJob.java
  src/main/java/com/junwoo/ott/global/batch/reader/CouponIssuanceReader.java
Labels: bug

#48 [Remove] 프론트엔드 코드 삭제
  build.gradle
  src/main/resources/static/css/style.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
  src/main/resources/static/js/fail.js
  src/main/resources/static/js/payment.js
  src/main/resources/static/js/success.js
  src/main/resources/static/payment/fail.html
  src/main/resources/static/payment/payment.html
  src/main/resources/static/payment/success.html
Labels: remove

#54 👔 fix(coupon): 이미 발행된 쿠폰의 중복 발생 문제 해결
  src/main/java/com/junwoo/ott/domain/coupon/repository/CouponIssuanceRepository.java
  src/main/java/com/junwoo/ott/domain/coupon/service/CouponService.java
Labels: bug

#57 🩹 fix(elastic): 랜덤으로 10개 가져오는 메서드 수정
  src/main/java/com/junwoo/ott/global/search/service/SearchService.java
Labels: enhancement

#58 [Fix] fix cors issue occured by http method types
  src/main/java/com/junwoo/ott/global/config/CorsConfiguration.java
Labels: enhancement

#65 🩹 fix(chart): ResponseDto 반환타입으로 수정
  src/main/java/com/junwoo/ott/domain/chart/controller/ChartController.java
Labels: bug

#68 ♻️ refactor(elastic): videoResponseDto 필드 스네이크 -> 카멜로 변경
  src/main/java/com/junwoo/ott/global/search/dto/body/VideoDto.java
  src/main/java/com/junwoo/ott/global/search/dto/body/VideoRandomDto.java
  src/main/java/com/junwoo/ott/global/search/dto/response/VideoRandomResponseDto.java
  src/main/java/com/junwoo/ott/global/search/dto/response/VideoResponseDto.java
  src/main/java/com/junwoo/ott/global/search/service/SearchService.java
Labels: bug

#69 🩹 fix(lock): 락이 걸린 메서드에서 exception 발생 시 lock 해제 오류 수정
  src/main/java/com/junwoo/ott/domain/coupon/service/CouponLockService.java
  src/main/java/com/junwoo/ott/global/aop/LockAspect.java
Labels: bug

#74 :fire: 사용하지 않는 도메인 삭제
  src/main/java/com/junwoo/ott/domain/actor/entity/Actor.java
  src/main/java/com/junwoo/ott/domain/actor/entity/VideoActor.java
  src/main/java/com/junwoo/ott/domain/actor/repository/ActorJpaRepository.java
  src/main/java/com/junwoo/ott/domain/actor/repository/VideoActorJpaRepository.java
  src/main/java/com/junwoo/ott/domain/comment/entity/Comment.java
  src/main/java/com/junwoo/ott/domain/comment/repository/CommentJpaRepository.java
  src/main/java/com/junwoo/ott/domain/director/entity/Director.java
  src/main/java/com/junwoo/ott/domain/director/entity/VideoDirector.java
  src/main/java/com/junwoo/ott/domain/director/repository/DirectorJpaRepository.java
  src/main/java/com/junwoo/ott/domain/director/repository/VideoDirectorJpaRepository.java
  src/main/java/com/junwoo/ott/domain/favorite/entity/Favorite.java
  src/main/java/com/junwoo/ott/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/junwoo/ott/domain/star/entity/Star.java
  src/main/java/com/junwoo/ott/domain/star/repository/StarRepository.java
Labels: remove

#78 🩹 fix(elastic): 제목 한글자 검색 기능 적용
  src/main/java/com/junwoo/ott/global/customenum/SearchType.java
  src/main/java/com/junwoo/ott/global/search/service/SearchService.java
Labels: enhancement

#80 [Refactor] dto 패키지 이동
  src/main/java/com/junwoo/ott/domain/payment/controller/OrderController.java
  src/main/java/com/junwoo/ott/domain/payment/dto/request/OrderReadRequestDto.java
  src/main/java/com/junwoo/ott/domain/payment/dto/response/OrderReadResponseDto.java
  src/main/java/com/junwoo/ott/domain/payment/service/OrderService.java
Labels: enhancement

#81 Readme 업데이트
  Readme.md
Labels: documentation
